### PR TITLE
feat/omapi_plugin_update

### PR DESCRIPTION
**Pull request by ocfmem**
Replace feat/se_omapi_plugin

Signed-off-by: Meddy Menzikoff <m.menzikoff@oneclickflare.fr>

### CODE REVIEW

**Comment by odelcroi** [comment]
retest this please

**Comment by ocfmem** [comment]
@pterr I have updated the project as you suggested on most elements.
Switched back source and target compatibility to 1.6, to be compliant with the project java source code. But as plugin is now using Kotlin, it's the Kotlin bytecode generator that handle compatibility with old Android Version as far as I know. 
I hade to force push because I rebased last changes from eclipse/keyple-java to retrieve last version of ReleaseNote.md

**Comment by ocfmem** [comment]
retest this please

**Comment by odelcroi** [comment]
retest this please

**Pull request merged**
