### PR TITLE
Commit gradle wrapper

### PR DESCRIPTION
**Pull request by tdassonville**
The whole point of the wrapper is to be included in the repo.
This initial commit upgrades to gradle 5.5, hence targeting gradle plugin 3.4.2 for android parts.

### CODE REVIEW

**Comment by odelcroi** [comment]
Eclipse's policy does not allow to upload jar file to repository. Should we consider the upgrade to gradle 5.5 anyway?

**Comment by tdassonville** [comment]
There is no "binary" or jar file in the PR. The gradle wrapper is made of executable scripts (gradlew is a sh script, gradlew.bat is a bat script), that are both quite human readable and freely licensed to be redistributed. When executed by the user, they download the appropriate binaries. So unless I miss something, I don't see it violating Eclipse policy.

**Comment by tdassonville** [comment]
My bad, I was convinced the jar was downloaded by the scripts.
If that's a strict policy, I guess that means we have no choice but to forgive about gradle wrapper :-(

**Comment by tdassonville** [comment]
Regarding gradle and gradle plugin versions, I'd definitely upgrade them periodically to stay in sync with the community (Android devs are using recent version)

**Comment by odelcroi** [comment]
Thanks for your contribution, we'll add an upgrade of gradle version in the backlog

**Pull request closed without merging**
